### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by EzekielWachira** [TheChance101/AAY-chart#89]
```
FATAL EXCEPTION: main
Process: com.example.swiftpay, PID: 4648
java.lang.NoSuchMethodError: No static method drawText-O6gbksU$default(Landroidx/compose/
	at com.aay.compose.baseComponents.XAxisDrawingKt.xAxisDrawing-6ZxE2Lo(XAxisDrawing.kt
	at com.aay.compose.baseComponents.BaseChartContainerKt.baseChartContainer-obdOQcU(Bas
	at com.aay.compose.lineChart.ChartContentKt$ChartContent$2.invoke(ChartContent.kt:81)
	at com.aay.compose.lineChart.ChartContentKt$ChartContent$2.invoke(ChartContent.kt:65)
	at androidx.compose.ui.draw.DrawBackgroundModifier.draw(DrawModifier.kt:116)
	at androidx.compose.ui.node.LayoutNodeDrawScope.drawDirect-x_KDEd0$ui_release(LayoutN
	at androidx.compose.ui.node.LayoutNodeDrawScope.draw-x_KDEd0$ui_release(LayoutNodeDra
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinato
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:354)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierN
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinato
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:354)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierN
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinato
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:354)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierN
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinato
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:354)
	at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:929)
	at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinato
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:354)
	at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:929)
	at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinato
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:354)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierN
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinato
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:354)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierN
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinato
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:354)
	at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:929)
	at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinato
	at androidx.compose.ui.node.NodeCoordinator.access$drawContainedDrawModifiers(NodeCoo
	at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:384)
	at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:383)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2303)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStat
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapsh
	at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:383)
	at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:54)
	at androidx.compose.ui.platform.RenderNodeApi29.record(RenderNodeApi29.android.kt:209
	at androidx.compose.ui.platform.RenderNodeLayer.updateDisplayList(RenderNodeLayer.and
	at androidx.compose.ui.platform.RenderNodeLayer.drawLayer(RenderNodeLayer.android.kt:
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:349)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierN
	at androidx.compose.ui.node.LayoutNodeDrawScope.drawContent(LayoutNodeDrawScope.kt:66
	at androidx.compose.foundation.BackgroundNode.draw(Background.kt:156)
	at androidx.compose.ui.node.LayoutNodeDrawScope.drawDirect-x_KDEd0$ui_release(LayoutN
	at androidx.compose.ui.node.LayoutNodeDrawScope.performDraw(LayoutNodeDrawScope.kt:76
	at androidx.compose.ui.node.LayoutNodeDrawScope.drawContent(LayoutNodeDrawScope.kt:55
	at androidx.compose.foundation.BorderModifierNode$drawRoundRectBorder$1.invoke(Border
	at androidx.compose.foundation.BorderModifierNode$drawRoundRectBorder$1.invoke(Border
	at androidx.compose.ui.draw.CacheDrawModifierNodeImpl.draw(DrawModifier.kt:221)
	at androidx.compose.ui.node.LayoutNodeDrawScope.drawDirect-x_KDEd0$ui_release(LayoutN
	at androidx.compose.ui.node.LayoutNodeDrawScope.draw-x_KDEd0$ui_release(LayoutNodeDra
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinato
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:354)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierN
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinato
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:354)
	at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:929)
	at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinato
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:354)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierN
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinato
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:354)
	at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:929)
	at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinato
	at androidx.compose.ui.node.NodeCoordinator.access$drawContainedDrawModifiers(NodeCoo
	at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:384)
	at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:383)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2303)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStat
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapsh
	at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:383)
	at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:54)
	at androidx.compose.ui.platform.RenderNodeApi29.record(RenderNodeApi29.android.kt:209
	at androidx.compose.ui.platform.RenderNodeLayer.updateDisplayList(RenderNodeLayer.and
	at androidx.compose.ui.platform.RenderNodeLayer.drawLayer(RenderNodeLayer.android.kt:
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:349)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierN
	at androidx.compose.ui.node.LayoutNodeDrawScope.drawContent(LayoutNodeDrawScope.kt:66
	at androidx.compose.foundation.DrawOverscrollModifier.draw(AndroidOverscroll.kt:80)
	at androidx.compose.ui.node.BackwardsCompatNode.draw(BackwardsCompatNode.kt:349)
	at androidx.compose.ui.node.LayoutNodeDrawScope.drawDirect-x_KDEd0$ui_release(LayoutN
	at androidx.compose.ui.node.LayoutNodeDrawScope.draw-x_KDEd0$ui_release(LayoutNodeDra
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinato
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:354)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierN
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinato
	at androidx.compose.ui.node.NodeCoordinator.access$drawContainedDrawModifiers(NodeCoo
	at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:384)
	at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:383)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2303)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStat
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapsh
	at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:383)
	at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:54)
	at androidx.compose.ui.platform.RenderNodeApi29.record(RenderNodeApi29.android.kt:209
	at androidx.compose.ui.platform.RenderNodeLayer.updateDisplayList(RenderNodeLayer.and
	at androidx.compose.ui.platform.RenderNodeLayer.drawLayer(RenderNodeLayer.android.kt:
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:349)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierN
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinato
	at androidx.compose.ui.node.NodeCoordinator.access$drawContainedDrawModifiers(NodeCoo
	at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:384)
	at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:383)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2303)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStat
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapsh
	at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:383)
	at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:54)
	at androidx.compose.ui.platform.RenderNodeApi29.record(RenderNodeApi29.android.kt:209
	at androidx.compose.ui.platform.RenderNodeLayer.updateDisplayList(RenderNodeLayer.and
	at androidx.compose.ui.platform.RenderNodeLayer.drawLayer(RenderNodeLayer.android.kt:
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:349)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierN
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinato
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:354)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierN
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinato
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:354)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierN
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinato
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:354)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierN
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinato
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:354)
	at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:929)
	at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinato
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:354)
	at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:929)
	at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinato
	at androidx.compose.ui.node.NodeCoordinator.access$drawContainedDrawModifiers(NodeCoo
	at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:384)
	at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:383)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2303)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStat
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapsh
	at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:383)
	at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:54)
	at androidx.compose.ui.platform.RenderNodeApi29.record(RenderNodeApi29.android.kt:209
	at androidx.compose.ui.platform.RenderNodeLayer.updateDisplayList(RenderNodeLayer.and
	at androidx.compose.ui.platform.RenderNodeLayer.drawLayer(RenderNodeLayer.android.kt:
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:349)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierN
	at androidx.compose.ui.node.LayoutNodeDrawScope.drawContent(LayoutNodeDrawScope.kt:66
	at androidx.compose.foundation.BackgroundNode.draw(Background.kt:156)
	at androidx.compose.ui.node.LayoutNodeDrawScope.drawDirect-x_KDEd0$ui_release(LayoutN
	at androidx.compose.ui.node.LayoutNodeDrawScope.draw-x_KDEd0$ui_release(LayoutNodeDra
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinato
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:354)
	at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:929)
	at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinato
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:354)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierN
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinato
	at androidx.compose.ui.node.NodeCoordinator.access$drawContainedDrawModifiers(NodeCoo
	at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:384)
	at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:383)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2303)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStat
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapsh
	at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:383)
	at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:54)
	at androidx.compose.ui.platform.RenderNodeApi29.record(RenderNodeApi29.android.kt:209
	at androidx.compose.ui.platform.RenderNodeLayer.updateDisplayList(RenderNodeLayer.and
	at androidx.compose.ui.platform.RenderNodeLayer.drawLayer(RenderNodeLayer.android.kt:
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:349)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierN
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinato
	at androidx.compose.ui.node.NodeCoordinator.access$drawContainedDrawModifiers(NodeCoo
	at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:384)
	at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:383)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2303)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStat
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapsh
	at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:383)
	at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:54)
	at androidx.compose.ui.platform.RenderNodeApi29.record(RenderNodeApi29.android.kt:209
	at androidx.compose.ui.platform.RenderNodeLayer.updateDisplayList(RenderNodeLayer.and
	at androidx.compose.ui.platform.RenderNodeLayer.drawLayer(RenderNodeLayer.android.kt:
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:349)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierN
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinato
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:354)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierN
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinato
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:354)
	at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:929)
	at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinato
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:354)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierN
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinato
	at androidx.compose.ui.node.NodeCoordinator.access$drawContainedDrawModifiers(NodeCoo
	at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:384)
	at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:383)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2303)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStat
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapsh
	at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:383)
	at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:54)
	at androidx.compose.ui.platform.RenderNodeApi29.record(RenderNodeApi29.android.kt:209
	at androidx.compose.ui.platform.RenderNodeLayer.updateDisplayList(RenderNodeLayer.and
	at androidx.compose.ui.platform.RenderNodeLayer.drawLayer(RenderNodeLayer.android.kt:
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:349)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierN
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinato
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:354)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierN
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinato
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:354)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierN
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinato
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:354)
	at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:929)
	at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinato
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:354)
	at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:929)
	at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinato
	at androidx.compose.ui.node.NodeCoordinator.access$drawContainedDrawModifiers(NodeCoo
	at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:384)
	at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:383)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2303)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStat
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapsh
	at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:383)
	at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:54)
	at androidx.compose.ui.platform.RenderNodeApi29.record(RenderNodeApi29.android.kt:209
	at androidx.compose.ui.platform.RenderNodeLayer.updateDisplayList(RenderNodeLayer.and
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.an
	at android.view.View.draw(View.java:24409)
	at android.view.View.updateDisplayListIfDirty(View.java:23267)
	at android.view.View.draw(View.java:24136)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
	at android.view.View.updateDisplayListIfDirty(View.java:23253)
	at android.view.View.draw(View.java:24136)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
	at android.view.View.updateDisplayListIfDirty(View.java:23253)
	at android.view.View.draw(View.java:24136)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
	at android.view.View.updateDisplayListIfDirty(View.java:23253)
	at android.view.View.draw(View.java:24136)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
	at com.android.internal.policy.DecorView.dispatchDraw(DecorView.java:1541)
	at android.view.View.draw(View.java:24409)
	at com.android.internal.policy.DecorView.draw(DecorView.java:1514)
	at android.view.View.updateDisplayListIfDirty(View.java:23267)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:777)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:783)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:881)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5647)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5330)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4486)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3116)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10885)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1301)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
	at android.view.Choreographer.doCallbacks(Choreographer.java:923)
	at android.view.Choreographer.doFrame(Choreographer.java:852)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757) at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

```

**Comment by AndrewAboalhana** [comment]
what is your compose version?

**Comment by EzekielWachira** [comment]
`2023.09.00`

**Comment by AndrewAboalhana** [comment]
Try to change your emulator that working on it and try API 33

**Comment by MahmoudMabrok** [comment]
if it need a specific compose version as minimum required please this at README. @AndrewAboalhana
